# Generated by Django 2.2.17 on 2021-02-07 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='update_time',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='update_time',
            new_name='update_time',
        ),
    ]
